In [3]:
import numpy as np

In [4]:
def Kmeans(data, initial_centroids, max_iter):
    n = data.shape[0]
    k = initial_centroids.shape[0]
    count = 0
    centroids = initial_centroids
    while count < max_iter:
        # assign clusters to each instance
        dis = np.zeros(shape=(n,k))
        for i in range(n):
            for j in range(k):
                dis[i][j] = np.sum(np.square(data[i,:] - centroids[j,:]))

        clusters = np.argmin(dis, axis=1)
        # update centroids
        for i in range(k):
            centroids[i] = np.mean(data[clusters == i], axis=0)
        count += 1
    return centroids


In [16]:
def KmeansPlusPlus(data, k):
    # automatic initialize centroids
    # note: the initialized centroids are instances
    n = data.shape[0]
    initial_centroids = []
    p = np.ones(shape=(n,))*(1/n) #initilize probability
    dis = np.zeros(shape=(k, n)) # here we store the distance of instances to each centroid
    for i in range(k):
        index = np.random.choice(n, size=1, p=p)   # sample 1 row index
        initial_centroids.append(data[index[0]])  # get the actual row from data
        for j in range(n):
            dis[i,j] = np.sum(np.square(data[j,:] -  initial_centroids[-1]))
        # update probability
        p = np.square(np.min(dis[:i+1,:], axis = 0)) / np.sum(np.square(np.min(dis[:i+1,:], axis = 0)))

    return initial_centroids



In [17]:
points = [(1, 2), (1, 4), (1, 0), (10, 2), (10, 4), (10, 0)]
data = np.array(points, dtype=float)
KmeansPlusPlus(data, 2)

[array([1., 4.]), array([10.,  2.])]

In [7]:
n = 100
np.ones(shape=(n,))*(1/n)

array([0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01])

In [15]:
points = [(1, 2), (1, 4), (1, 0), (10, 2), (10, 4), (10, 0)]
k = 2
initial_centroids = [(1, 1), (10, 1)]
max_iterations = 10

In [16]:
np.array(points)

array([[ 1,  2],
       [ 1,  4],
       [ 1,  0],
       [10,  2],
       [10,  4],
       [10,  0]])

In [ ]:
data = np.array(points, dtype=float)
initial_centroids = np.array(initial_centroids, dtype=float)

In [11]:
data.shape

(6, 2)

In [12]:
initial_centroids.shape

(2, 2)

In [14]:
Kmeans(data, initial_centroids, max_iter=10)

array([[ 1,  2],
       [10,  2]])