In [1]:
import numpy as np

In [4]:
np.random.choice(np.arange(100), size=100, replace=True)

array([85, 39, 97, 31, 23, 28, 27, 74, 60,  0, 92, 98, 44, 50, 23, 34, 90,
       91, 16, 46,  9, 36, 44, 61, 67, 46, 55, 51, 25, 36, 97, 97,  2, 68,
       68, 71, 24, 68, 91, 21, 76, 94, 93, 12, 56, 79, 61, 29, 81,  3, 18,
       33, 78, 13, 88, 11, 99, 55,  0, 10, 99, 25, 64,  7,  0, 99, 10, 87,
       98, 74, 90, 54, 72, 57, 48, 84, 14, 48,  5, 54, 83, 21, 97,  0, 35,
       12, 12, 87, 12,  8, 45, 29, 75, 97, 54, 21, 93, 56,  9, 19])

In [ ]:
def get_random_subsets(X, y, n_subsets, replacements=True, seed=42):
    np.random.seed(seed)
    n, m = X.shape
    res = []
    for _ in range(n_subsets):
        if replacements == True:
            indexes = np.random.choice(np.arange(n), size = n, replace = True)
        else:
            indexes = np.random.choice(np.arange(n), size = n//2, replace = False)
        
        res.append([X[indexes], y[indexes]])
    return res

In [9]:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]) 
y = np.array([1, 2, 3, 4, 5])

In [11]:
get_random_subsets(X, y, 3, False)

[[array([[ 3,  4],
         [ 9, 10]]),
  array([2, 5])],
 [array([[7, 8],
         [3, 4]]),
  array([4, 2])],
 [array([[3, 4],
         [1, 2]]),
  array([2, 1])]]